version: '2'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}
    nodeexporter: {}

services:

  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.size=25GB'
      - '--web.enable-lifecycle'
    restart: always
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./node-exporter:/etc/node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.processes'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.netstat.fields=(.*)'
      - '--collector.vmstat.fields=(.*)'
      - '--collector.interrupts'
    restart: always
    expose:
      - 9100
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:6.3.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  armexporter:
    image: carlosedp/arm_exporter
    restart: unless-stopped
    ports:
      - 9243
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  airfilterexporter:
    image: airfilter/exporter
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/:/dev/
    ports:
      - "9600:9600"
    expose:
      - 9600
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  airfilterfancontroller:
    image: airfilter/fan_controller
    restart: unless-stopped
    privileged: true
    volumes:
      - /sys/class/pwm/:/sys/class/pwm/
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    command: ["python3", "-u", "fan-controller.py", "http://prometheus:9090" ,"sum(avg_over_time(airfilter_dust[10m]))"]
    #command: ["sleep", "1000"]
    environment:
      - PWM0_PERIOD=40000
      - PWM1_PERIOD=40000
      - WEEK_RANGE=6
      - WORK_HOURS_FROM=8
      - WORK_HOURS_UNTIL=15
      - WEEK_HOME_FROM=17
      - WEEK_HOME_UNTIL=25
      - WEEK_END_HOME_FROM=8
      - WEEK_END_HOME_UNTIL=24
      - SPEED1=5000
      - SPEED2=9000
      - SPEED3=12000
      - SPEED4=18000
      - SPEED5=25000
      - SPEED6=30000
      - POLLUTION1=3
      - POLLUTION2=5
      - POLLUTION3=10
      - POLLUTION4=20
      - POLLUTION5=30
      - POLLUTION6=40
