{
 "title": "Open-Airfilter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Dust", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dust Raw",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airfilter_dust", "legendFormat": "{{ pm }}" }
   ]
  },
  {
   "title": "Avageraged Sum",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(airfilter_dust[10m]))",
     "legendFormat": "Avageraged Sum"
    }
   ]
  },
  { "title": "Temperature and Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(airfilter_humidity[5m])",
     "legendFormat": "humidity"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(airfilter_temperature[5m])",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "RPI Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rpi_cpu_temperature_celsius[5m])",
     "legendFormat": "raspberry temperature"
    }
   ]
  },
  {
   "title": "eco2 and tvoc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "eco2",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(airfilter_eco2[5m])",
       "legendFormat": "eco2"
      }
     ]
    },
    {
     "title": "tvoc",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(airfilter_tvoc[5m])",
       "legendFormat": "tvoc"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "CCS811 Errors",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "airfilter_error", "legendFormat": "error" }
     ]
    },
    {
     "title": "CCS811 Samples available",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "airfilter_samples", "legendFormat": "samples" }
     ]
    },
    {
     "title": "CCS811 Valid Result",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "airfilter_result", "legendFormat": "result" }
     ]
    }
   ]
  }
 ]
}